# Generated by Django 2.0 on 2018-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='last_enter',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
