# Generated by Django 2.0 on 2018-01-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_features_last_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='image',
            field=models.ImageField(default=1, upload_to='static/'),
            preserve_default=False,
        ),
    ]
