# Generated by Django 2.0 on 2018-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_features_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.ImageField(upload_to='staticfiles/p_images/'),
        ),
    ]
