# Generated by Django 2.0 on 2018-01-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180123_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.ImageField(upload_to='static/p_images/'),
        ),
    ]
