# Generated by Django 2.0 on 2018-02-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20180123_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.ImageField(upload_to='staticfiles/chat/p_images/'),
        ),
    ]
